name: scroll_navigation
description: It's a powerful navigation by gestures and taps. You can scroll from left to right or tap on the navigation icons.
version: 1.2.0
homepage: https://github.com/seel-channel/scroll_navigation

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  helpers: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
