name: scroll_navigation
description: It's a powerful navigation by gestures and taps. You can scroll from left to right or tap on the navigation icons.
version: 1.3.1
homepage: https://github.com/seel-channel/scroll_navigation

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  helpers: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
