name: scroll_navigation
description: It is a navigation by gestures and taps. You can scroll from left to right or tap on the navigation icons.
version: 1.0.2
homepage: https://github.com/seel-channel/scroll_navigation

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
